/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import javax.swing.JOptionPane;
import model.BankAcct;
import model.BankAcctHistory;

/**
 *
 * @author lydia
 */
public class BankAcctCreateJPanel extends javax.swing.JPanel {

    /**
     * Creates new form bankAcctCreateJPanel
     */
    
    BankAcctHistory bankAcctHistory;
    public BankAcctCreateJPanel(BankAcctHistory bankAcctHistory) {
        initComponents();
        this.bankAcctHistory = bankAcctHistory;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblAcctBalance = new javax.swing.JLabel();
        txtAcctNumber = new javax.swing.JTextField();
        txtName = new javax.swing.JTextField();
        txtBankName = new javax.swing.JTextField();
        txtAcctType = new javax.swing.JTextField();
        txtAcctBalance = new javax.swing.JTextField();
        lblTitle = new javax.swing.JLabel();
        btnSave = new javax.swing.JButton();
        lblName = new javax.swing.JLabel();
        lblAcctNumber = new javax.swing.JLabel();
        lblBankName = new javax.swing.JLabel();
        lblAcctType = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 204, 204));

        lblAcctBalance.setText("Account Balance:");

        txtAcctNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAcctNumberActionPerformed(evt);
            }
        });

        txtAcctBalance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAcctBalanceActionPerformed(evt);
            }
        });

        lblTitle.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("Create Bank Account");

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        lblName.setText("Name:");

        lblAcctNumber.setText("Account Number:");

        lblBankName.setText("Bank name:");

        lblAcctType.setText("Account Type:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(102, 102, 102)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblAcctBalance)
                    .addComponent(lblAcctType)
                    .addComponent(lblBankName)
                    .addComponent(lblAcctNumber)
                    .addComponent(lblName))
                .addGap(149, 149, 149)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtBankName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAcctType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAcctBalance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtName, javax.swing.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE)
                    .addComponent(txtAcctNumber))
                .addContainerGap(187, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSave)
                .addGap(255, 255, 255))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {txtAcctBalance, txtAcctNumber, txtAcctType, txtBankName, txtName});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(lblTitle)
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblName)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAcctNumber)
                    .addComponent(txtAcctNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBankName)
                    .addComponent(txtBankName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAcctType)
                    .addComponent(txtAcctType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAcctBalance)
                    .addComponent(txtAcctBalance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(btnSave)
                .addContainerGap(162, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtAcctNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAcctNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAcctNumberActionPerformed

    private void txtAcctBalanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAcctBalanceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAcctBalanceActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        
        String name = txtName.getText();
        String acctNumber = txtAcctNumber.getText();
        String bankName = txtBankName.getText();
        String acctType = txtAcctType.getText();
        String acctBalance = txtAcctBalance.getText();
        
        BankAcct ba = bankAcctHistory.addNewBankAcct();
        
        ba.setAcctBalance(acctBalance);
        ba.setAcctNumber(acctNumber);
        ba.setAcctType(acctType);
        ba.setBankName(bankName);
        ba.setName(name);
        
        JOptionPane.showMessageDialog(this, "New Bank Account added.");
        
        txtName.setText("");
        txtAcctNumber.setText("");
        txtBankName.setText("");
        txtAcctType.setText("");
        txtAcctBalance.setText("");
    }//GEN-LAST:event_btnSaveActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSave;
    private javax.swing.JLabel lblAcctBalance;
    private javax.swing.JLabel lblAcctNumber;
    private javax.swing.JLabel lblAcctType;
    private javax.swing.JLabel lblBankName;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTextField txtAcctBalance;
    private javax.swing.JTextField txtAcctNumber;
    private javax.swing.JTextField txtAcctType;
    private javax.swing.JTextField txtBankName;
    private javax.swing.JTextField txtName;
    // End of variables declaration//GEN-END:variables
}
