/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;

import model.BankAcctHistory;
import model.HomeAddHistory;
import model.LocalAddHistory;
import model.PersonHistory;

/**
 *
 * @author lydia
 */
public class MainJFrame extends javax.swing.JFrame {

    /**
     * Creates new form mainJFrame
     */
    
    PersonHistory personHistory;
    LocalAddHistory localAddHistory;
    HomeAddHistory homeAddHistory;
    BankAcctHistory bankAcctHistory;
    
    public MainJFrame() {
        initComponents();
        
        personHistory = new PersonHistory();
        localAddHistory = new LocalAddHistory();
        homeAddHistory = new HomeAddHistory();
        bankAcctHistory = new BankAcctHistory();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        splitPane = new javax.swing.JSplitPane();
        controlPanel = new javax.swing.JPanel();
        btnCreatePerson = new javax.swing.JButton();
        btnViewPerson = new javax.swing.JButton();
        btnCreateHomeAdd = new javax.swing.JButton();
        btnViewHomeAdd = new javax.swing.JButton();
        btnCreateLocalAdd = new javax.swing.JButton();
        btnViewLocalAdd = new javax.swing.JButton();
        btnCreateBankAcct = new javax.swing.JButton();
        btnViewBankAcct = new javax.swing.JButton();
        lblPersonProfile = new javax.swing.JLabel();
        workArea = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        controlPanel.setBackground(new java.awt.Color(255, 204, 204));

        btnCreatePerson.setText("Create Person");
        btnCreatePerson.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreatePersonActionPerformed(evt);
            }
        });

        btnViewPerson.setText("View Person");
        btnViewPerson.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewPersonActionPerformed(evt);
            }
        });

        btnCreateHomeAdd.setText("Create Home Address");
        btnCreateHomeAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateHomeAddActionPerformed(evt);
            }
        });

        btnViewHomeAdd.setText("View Home Address");
        btnViewHomeAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewHomeAddActionPerformed(evt);
            }
        });

        btnCreateLocalAdd.setText("Create Local Address");
        btnCreateLocalAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateLocalAddActionPerformed(evt);
            }
        });

        btnViewLocalAdd.setText("View Local Address");
        btnViewLocalAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewLocalAddActionPerformed(evt);
            }
        });

        btnCreateBankAcct.setText("Create Bank Account");
        btnCreateBankAcct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateBankAcctActionPerformed(evt);
            }
        });

        btnViewBankAcct.setText("View Bank Account");
        btnViewBankAcct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewBankAcctActionPerformed(evt);
            }
        });

        lblPersonProfile.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        lblPersonProfile.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPersonProfile.setText("Person Profile");

        javax.swing.GroupLayout controlPanelLayout = new javax.swing.GroupLayout(controlPanel);
        controlPanel.setLayout(controlPanelLayout);
        controlPanelLayout.setHorizontalGroup(
            controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(controlPanelLayout.createSequentialGroup()
                .addGroup(controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, controlPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblPersonProfile, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btnCreatePerson)
                        .addComponent(btnViewPerson)
                        .addComponent(btnCreateHomeAdd)
                        .addComponent(btnViewHomeAdd)
                        .addComponent(btnCreateLocalAdd)
                        .addComponent(btnViewBankAcct, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(btnViewLocalAdd)
                        .addComponent(btnCreateBankAcct)))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        controlPanelLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnCreateBankAcct, btnCreateHomeAdd, btnCreateLocalAdd, btnCreatePerson, btnViewBankAcct, btnViewHomeAdd, btnViewLocalAdd, btnViewPerson});

        controlPanelLayout.setVerticalGroup(
            controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(controlPanelLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(lblPersonProfile)
                .addGap(27, 27, 27)
                .addComponent(btnCreatePerson)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnViewPerson)
                .addGap(18, 18, 18)
                .addComponent(btnCreateHomeAdd)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnViewHomeAdd)
                .addGap(18, 18, 18)
                .addComponent(btnCreateLocalAdd)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnViewLocalAdd)
                .addGap(18, 18, 18)
                .addComponent(btnCreateBankAcct)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnViewBankAcct)
                .addContainerGap(113, Short.MAX_VALUE))
        );

        splitPane.setLeftComponent(controlPanel);

        workArea.setBackground(new java.awt.Color(255, 204, 153));

        javax.swing.GroupLayout workAreaLayout = new javax.swing.GroupLayout(workArea);
        workArea.setLayout(workAreaLayout);
        workAreaLayout.setHorizontalGroup(
            workAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 678, Short.MAX_VALUE)
        );
        workAreaLayout.setVerticalGroup(
            workAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 458, Short.MAX_VALUE)
        );

        splitPane.setRightComponent(workArea);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(splitPane)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(splitPane)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCreatePersonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreatePersonActionPerformed
        // TODO add your handling code here:
        PersonCreateJPanel personCreatePanel = new PersonCreateJPanel(personHistory);
        splitPane.setRightComponent(personCreatePanel);
        
    }//GEN-LAST:event_btnCreatePersonActionPerformed

    private void btnViewPersonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewPersonActionPerformed
        // TODO add your handling code here:
        
       PersonViewJPanel personViewPanel = new PersonViewJPanel(personHistory);
       splitPane.setRightComponent(personViewPanel);
    }//GEN-LAST:event_btnViewPersonActionPerformed

    private void btnViewBankAcctActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewBankAcctActionPerformed
        // TODO add your handling code here:
        
        BankAcctViewJPanel bankAcctViewPanel = new BankAcctViewJPanel(bankAcctHistory);
        splitPane.setRightComponent(bankAcctViewPanel);
    }//GEN-LAST:event_btnViewBankAcctActionPerformed

    private void btnCreateHomeAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateHomeAddActionPerformed
        // TODO add your handling code here:
        HomeAddCreateJPanel homeAddCreatePanel = new HomeAddCreateJPanel(homeAddHistory);
        splitPane.setRightComponent(homeAddCreatePanel);
    }//GEN-LAST:event_btnCreateHomeAddActionPerformed

    private void btnCreateLocalAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateLocalAddActionPerformed
        // TODO add your handling code here:
        LocalAddCreateJPanel localAddCreatePanel = new LocalAddCreateJPanel(localAddHistory);
        splitPane.setRightComponent(localAddCreatePanel);
    }//GEN-LAST:event_btnCreateLocalAddActionPerformed

    private void btnCreateBankAcctActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateBankAcctActionPerformed
        // TODO add your handling code here:
        BankAcctCreateJPanel bankAcctCreatePanel = new BankAcctCreateJPanel(bankAcctHistory);
        splitPane.setRightComponent(bankAcctCreatePanel);
    }//GEN-LAST:event_btnCreateBankAcctActionPerformed

    private void btnViewHomeAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewHomeAddActionPerformed
        // TODO add your handling code here:
        HomeAddViewJPanel homeAddViewPanel = new HomeAddViewJPanel(homeAddHistory);
        splitPane.setRightComponent(homeAddViewPanel);
    }//GEN-LAST:event_btnViewHomeAddActionPerformed

    private void btnViewLocalAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewLocalAddActionPerformed
        // TODO add your handling code here:
        
        LocalAddViewJPanel localAddViewPanel = new LocalAddViewJPanel(localAddHistory);
        splitPane.setRightComponent(localAddViewPanel);
    }//GEN-LAST:event_btnViewLocalAddActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCreateBankAcct;
    private javax.swing.JButton btnCreateHomeAdd;
    private javax.swing.JButton btnCreateLocalAdd;
    private javax.swing.JButton btnCreatePerson;
    private javax.swing.JButton btnViewBankAcct;
    private javax.swing.JButton btnViewHomeAdd;
    private javax.swing.JButton btnViewLocalAdd;
    private javax.swing.JButton btnViewPerson;
    private javax.swing.JPanel controlPanel;
    private javax.swing.JLabel lblPersonProfile;
    private javax.swing.JSplitPane splitPane;
    private javax.swing.JPanel workArea;
    // End of variables declaration//GEN-END:variables
}
